/* Offline source inspection; no gameplay logic or inferred collision semantics. */
'use strict';
const $=id=>document.getElementById(id),D=window.DATA;
const table=name=>D.tables[name]||[],mapRows=new Map(table('map').map(x=>[x.id,x])),maps=new Map(D.maps.map(x=>[x.id,x]));
const canvas=$('map-canvas'),ctx=canvas.getContext('2d');let current=null,records=[],camera={x:0,y:0},scale=20,visibleLayers=new Set(),images=new Map(),loadToken=0;
const colors={npcs:'#d0a6ff',warps:'#8fe0a2',teleports:'#76cfff',chests:'#ffd576',events:'#fc9b96'};
const glyph={npcs:'N',warps:'W',teleports:'T',chests:'C',events:'E'};
const mwidth=()=>+current.attributes.width,mheight=()=>+current.attributes.height;
const originY=y=>$('origin').value==='bottom'?mheight()-1-y:y;
const rawY=y=>$('origin').value==='bottom'?mheight()-1-y:y;
function el(tag,text,cls){let e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function fmt(value){return JSON.stringify(value,null,2);}
function listMaps(){let q=$('search').value.toLowerCase(),host=$('map-list');host.replaceChildren();let n=0;
 for(let row of table('map')){if(!(`${row.id} ${row.name}`.toLowerCase().includes(q)))continue;n++;let b=el('button',undefined,'map-option'+(current&&current.id===row.id?' active':''));b.dataset.mapId=row.id;b.append(el('span',String(row.id).padStart(3,'0'),'number'),document.createTextNode(row.name));b.onclick=()=>selectMap(row.id);host.append(b);} $('map-count').textContent=`${n} / ${maps.size}`;}
function makeRecords(mid){let list=[];function add(kind,t,row,x,y,extra={}){list.push({kind,table:t,id:row.id,row,x,y,...extra});}
 for(let r of table('map_npc').filter(x=>x.mapId===mid))add('npcs','map_npc',r,r.zeroPosX,r.zeroPosY,{dialogueId:r.storyId});
 for(let r of table('map_warp_point').filter(x=>x.cur_map_id===mid))add('warps','map_warp_point',r,r.point_x,r.point_y,{target:{id:r.tar_map_id,x:r.tar_hero_pos_x,y:r.tar_hero_pos_y}});
 for(let r of table('map_box').filter(x=>x.mapId===mid))add('chests','map_box',r,r.posX,r.posY);
 for(let r of table('auto_move').filter(x=>x.mapId===mid))add('events','auto_move',r,r.hero_posX,r.hero_posY);
 for(let r of table('map_object').filter(x=>x.map_id===mid))add('events','map_object',r,r.posX,r.posY);
 for(let r of table('story').filter(x=>String(x.nextSceneId)==='2'&&x.sceneParam===mid))add('teleports','story',r,r.tar_x,r.tar_y,{note:'根据 nextSceneId=2 推断：这是剧情传送终点，不代表触发点。'});
 let row=mapRows.get(mid);if(row.jump_map_id)add('warps','map',row,null,null,{note:'map.jump_map_id：触发位置/条件 UNKNOWN；这里只提供目标浏览。',target:{id:row.jump_map_id,x:row.jump_pos_x,y:row.jump_pos_y}});
 return list;}
function listRecords(){let host=$('record-list'),q=$('record-search').value.toLowerCase();host.replaceChildren();$('record-count').textContent=records.length;
 for(let r of records){if(!(`${r.table} ${r.id} ${r.kind}`.includes(q)))continue;let b=el('button',`${glyph[r.kind]} ${r.table} #${r.id}`,'record');b.dataset.record=`${r.table}:${r.id}`;b.append(el('small',r.x===null?'位置未知':`raw (${r.x}, ${r.y})`));b.onclick=()=>{inspect([r]);if(r.x!==null){camera.x=r.x+.5-canvas.clientWidth/(2*scale);camera.y=originY(r.y)+.5-canvas.clientHeight/(2*scale);draw();}};host.append(b);}}
function inspect(selected,tiles=[]){let host=$('details');host.replaceChildren();for(let r of selected){let c=el('div',undefined,'detail-card');c.append(el('h4',`${r.table} #${r.id}`));if(r.note)c.append(el('p',r.note));if(r.dialogueId){c.append(el('p','dialogue ID: '+r.dialogueId));let d=table('story').find(x=>x.id===r.dialogueId);if(d)c.append(el('p',d.speak_words));}
 if(r.target){let t=r.target;c.append(el('p',`目标 map ${t.id} · raw (${t.x}, ${t.y})`));let b=el('button','查看目标地图 '+t.id);b.className='jump-target';b.onclick=()=>selectMap(t.id,t);c.append(b);}
 let sid=`reference.${r.table.toLowerCase()}.${r.id}`;if(D.flags[sid])c.append(el('p','NON_ORIGINAL_REFERENCE_CONTENT · '+D.flags[sid].evidence.map(e=>e.marker).join(' / ')));
 c.append(el('pre',fmt(r.row)));c.append(el('p',`来源 MainData / ${r.table} / id=${r.id} · source.reference.${r.table.toLowerCase()}.${r.id}`));host.append(c);}
 if(tiles.length){let c=el('div',undefined,'detail-card');c.append(el('h4','此格 Tile / Collision 原始属性'),el('pre',fmt(tiles)));host.append(c);}if(!selected.length&&!tiles.length)host.textContent='该格没有已定位记录或非空 Tile 属性。';}
function tileset(gid){let best=null;for(let t of current.tilesets)if(+t.attributes.firstgid<=gid&&(!best||+t.attributes.firstgid>+best.attributes.firstgid))best=t;return best;}
function tileInfo(x,y){let out=[];if(x<0||y<0||x>=mwidth()||y>=mheight())return out;
 for(let l of current.layers){let raw=l.gids[y*mwidth()+x]>>>0,gid=raw&0x0fffffff;if(!gid)continue;let ts=tileset(gid);out.push({layer:l.attributes.name,gid,flipFlags:raw>>>28,tileId:ts?gid-(+ts.attributes.firstgid):null,properties:ts?(ts.tileProperties[gid-(+ts.attributes.firstgid)]||{}):{}});}return out;}
function fit(){let w=canvas.clientWidth,h=canvas.clientHeight;scale=Math.max(2,Math.min(48,Math.min(w/mwidth(),h/mheight())*.94));camera={x:(mwidth()-w/scale)/2,y:(mheight()-h/scale)/2};draw();}
function zoom(f,x=canvas.clientWidth/2,y=canvas.clientHeight/2){let wx=camera.x+x/scale,wy=camera.y+y/scale;scale=Math.max(2,Math.min(120,scale*f));camera={x:wx-x/scale,y:wy-y/scale};draw();}
function draw(){if(!current)return;let width=canvas.clientWidth,height=canvas.clientHeight,dpr=window.devicePixelRatio||1;if(canvas.width!==Math.round(width*dpr)||canvas.height!==Math.round(height*dpr)){canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,width,height);
 let x0=Math.max(0,Math.floor(camera.x)),y0=Math.max(0,Math.floor(camera.y)),x1=Math.min(mwidth(),Math.ceil(camera.x+width/scale)),y1=Math.min(mheight(),Math.ceil(camera.y+height/scale));
 for(let layer of current.layers){if(!visibleLayers.has(layer.attributes.name))continue;let opacity=layer.attributes.opacity===undefined?1:+layer.attributes.opacity;ctx.globalAlpha=opacity;
 for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){let raw=layer.gids[y*mwidth()+x]>>>0,gid=raw&0x0fffffff;if(!gid)continue;let ts=tileset(gid);if(!ts||!ts.image)continue;let im=images.get(ts.image.path);if(!im||!im.complete||!im.naturalWidth)continue;let tw=+ts.attributes.tilewidth,th=+ts.attributes.tileheight,cols=Math.floor(+ts.image.width/tw),local=gid-(+ts.attributes.firstgid),sx=(local%cols)*tw,sy=Math.floor(local/cols)*th,dx=(x-camera.x)*scale,dy=(y-camera.y)*scale;
 if(raw&0xf0000000){ctx.save();ctx.translate(dx+scale/2,dy+scale/2);if(raw&0x80000000)ctx.scale(-1,1);if(raw&0x40000000)ctx.scale(1,-1);if(raw&0x20000000)ctx.transform(0,1,1,0,0,0);ctx.drawImage(im,sx,sy,tw,th,-scale/2,-scale/2,scale,scale);ctx.restore();}else ctx.drawImage(im,sx,sy,tw,th,dx,dy,scale+.2,scale+.2);
 }}ctx.globalAlpha=1;
 if($('collision').checked){for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){let entries=tileInfo(x,y).filter(t=>Object.keys(t.properties).length);if(!entries.length)continue;let t=entries.find(t=>t.layer==='macair')||entries.find(t=>t.layer==='mac')||entries[0];ctx.fillStyle=t.layer==='macair'?'#c08bff66':t.layer==='mac'?'#ffae4866':'#6be5a166';ctx.fillRect((x-camera.x)*scale,(y-camera.y)*scale,scale,scale);}}
 if($('grid').checked&&scale>=10){ctx.strokeStyle='#bed4e326';ctx.lineWidth=.5;ctx.beginPath();for(let x=x0;x<=x1;x++){ctx.moveTo((x-camera.x)*scale,0);ctx.lineTo((x-camera.x)*scale,height);}for(let y=y0;y<=y1;y++){ctx.moveTo(0,(y-camera.y)*scale);ctx.lineTo(width,(y-camera.y)*scale);}ctx.stroke();}
 for(let r of records){if(r.x===null||!$(r.kind).checked)continue;let dx=(r.x+.5-camera.x)*scale,dy=(originY(r.y)+.5-camera.y)*scale;if(dx<-20||dy<-20||dx>width+20||dy>height+20)continue;let radius=Math.max(4,Math.min(10,scale*.4));ctx.fillStyle=colors[r.kind];ctx.strokeStyle='#10151e';ctx.lineWidth=1.5;ctx.beginPath();if(r.kind==='npcs')ctx.arc(dx,dy,radius,0,Math.PI*2);else ctx.rect(dx-radius,dy-radius,radius*2,radius*2);ctx.fill();ctx.stroke();if(scale>14){ctx.fillStyle='#13202c';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold 10px monospace';ctx.fillText(glyph[r.kind],dx,dy+.5);}}
}
async function selectMap(id,target){if(!maps.has(id)){$('details').textContent='目标地图不存在：'+id;return;}let token=++loadToken;current=maps.get(id);records=makeRecords(id);let row=mapRows.get(id);$('map-id').textContent='MAP '+String(id).padStart(3,'0');$('map-name').textContent=row.name;$('map-size').textContent=`${mwidth()} × ${mheight()} tiles · ${current.attributes.tilewidth}px`;document.title=`${id} ${row.name} · 地图取证台`;
 $('map-metadata').textContent=fmt({map:row,tmx:current.sourceFile,sha256:current.sha256,sourceRefs:current.sourceRefs,referenceCommit:D.commit,mapMasks:table('map_mask').filter(x=>x.map_id===id),caution:'图像以TMX声明宽度寻址；尺寸不符保留，不自动修补。map_mask和zeroPos字段语义未核。'});
 $('details').textContent='点击标记或下方记录查看原始字段。';$('record-search').value='';visibleLayers=new Set();$('layers').replaceChildren();for(let l of current.layers){let label=el('label'),cb=document.createElement('input');cb.type='checkbox';cb.checked=!['mac','macair','monster'].includes(l.attributes.name)&&l.attributes.visible!=='0';cb.dataset.layer=l.attributes.name;if(cb.checked)visibleLayers.add(l.attributes.name);cb.onchange=()=>{if(cb.checked)visibleLayers.add(l.attributes.name);else visibleLayers.delete(l.attributes.name);draw();};label.append(cb,document.createTextNode(l.attributes.name));$('layers').append(label);}
 listMaps();listRecords();fit();$('loading').hidden=false;let warnings=[];await Promise.all(current.tilesets.filter(t=>t.image).map(t=>new Promise(resolve=>{let path=t.image.path,im=images.get(path);const done=()=>{if(im.naturalWidth!==+t.image.width||im.naturalHeight!==+t.image.height)warnings.push(`${t.image.source}: 声明 ${t.image.width}×${t.image.height} / 实际 ${im.naturalWidth}×${im.naturalHeight}`);resolve();};if(im&&im.complete){done();return;}im=new Image();images.set(path,im);im.onload=done;im.onerror=()=>{warnings.push('缺失图片 '+path);resolve();};im.src=D.images[path];})));
 if(token!==loadToken)return;$('loading').hidden=true;let flagged=D.flags[`reference.map.${id}`];$('map-warning').textContent=(flagged?'NON_ORIGINAL_REFERENCE_CONTENT · ':'')+warnings.join('；');if(target){camera.x=target.x+.5-canvas.clientWidth/(2*scale);camera.y=originY(target.y)+.5-canvas.clientHeight/(2*scale);}draw();window.viewerState={mapId:id,records:records.length,loaded:true};}
let drag=null;
canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,cx:camera.x,cy:camera.y,moved:false};canvas.setPointerCapture(e.pointerId);};
canvas.onpointermove=e=>{let rect=canvas.getBoundingClientRect(),px=e.clientX-rect.left,py=e.clientY-rect.top;if(drag){if(Math.abs(e.clientX-drag.x)+Math.abs(e.clientY-drag.y)>4)drag.moved=true;if(drag.moved){camera.x=drag.cx-(e.clientX-drag.x)/scale;camera.y=drag.cy-(e.clientY-drag.y)/scale;draw();}}let x=Math.floor(camera.x+px/scale),y=Math.floor(camera.y+py/scale);$('coordinates').textContent=`TMX (${x}, ${y}) · raw (${x}, ${rawY(y)}) · ${scale.toFixed(1)} px/tile`;};
canvas.onpointerup=e=>{if(drag&&!drag.moved){let rect=canvas.getBoundingClientRect(),x=Math.floor(camera.x+(e.clientX-rect.left)/scale),y=Math.floor(camera.y+(e.clientY-rect.top)/scale);inspect(records.filter(r=>r.x===x&&originY(r.y)===y&&$(r.kind).checked),tileInfo(x,y));}drag=null;};canvas.onpointercancel=()=>{drag=null;};
canvas.addEventListener('wheel',e=>{e.preventDefault();let r=canvas.getBoundingClientRect();zoom(e.deltaY<0?1.15:1/1.15,e.clientX-r.left,e.clientY-r.top);},{passive:false});
$('search').oninput=listMaps;$('record-search').oninput=listRecords;$('fit').onclick=fit;$('zoom-in').onclick=()=>zoom(1.25);$('zoom-out').onclick=()=>zoom(.8);
for(let id of ['npcs','warps','teleports','chests','events','collision','grid','origin'])$(id).onchange=draw;
new ResizeObserver(()=>draw()).observe(canvas);selectMap(1);
